catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('recipes/', views.RecipeListView.as_view(), name='recipes'),
    path('recipe/<int:pk>', views.RecipeDetailView.as_view(), name='recipe-detail'),

]

recipes/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

# Use include() to add paths from the catalog application
from django.urls import include
from django.urls import path

urlpatterns += [
    path('catalog/', include('catalog.urls')),
]

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse # Used to generate URLs by reversing the URL patterns


# Create your models here.

class Ingredient(models.Model):
    """Model representing an ingredient. eg. onion, tomato, etc"""
    name = models.CharField(max_length=20, help_text='Enter an ingredient')
    
    def __str__(self):
        """String for representing the Model object."""
        return self.name

class Measurement(models.Model):
    """Model representing a type of measurement. eg. cup, teaspoon, gram, etc"""
    name = models.CharField(max_length=20, help_text='Enter a measurement type')

    def __str__(self):
        """String for representing the Model object."""
        return self.name


class Category(models.Model):
    """Model representing a recipe category. eg. desert, snack, cake, salad etc"""
    name = models.CharField(max_length=20, help_text='Enter a recipe category')
    
    def __str__(self):
        """String for representing the Model object."""
        return self.name


class Recipe(models.Model):
    """Model representing a recipe."""
    title = models.CharField(max_length=200)    
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the recipe')
    
    # method = models.ManyToManyField(RecipeStep, help_text='Select a step for this method')
    category = models.ManyToManyField(Category, help_text='Select a category for this recipe')
    
    # attribution = models.CharField(max_length=40) 
    prep_time = models.IntegerField()
    recipe_yield = models.CharField(max_length=20)
    ## ADD a picture option


    def __str__(self):
        """String for representing the Model object."""
        return self.title
    
    def get_absolute_url(self):
        """Returns the url to access a detail record for this recipe."""
        return reverse('recipe-detail', args=[str(self.id)])
    

class RecipeIngredient(models.Model):
    """Model representing an ingredient for a recipe. eg. onion, tomato, etc"""
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    measurement = models.ForeignKey(Measurement, blank=True, null=True, on_delete=models.CASCADE)
    quantity = models.IntegerField(help_text='Enter an ingredient')
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, default=1)

    def __str__(self):
        """String for representing the Model object."""
        if self.measurement:
            return str(self.quantity) + " " + str(self.measurement) + " " + str(self.ingredient)
        else:
            return str(self.quantity) + " " + str(self.ingredient)  


class RecipeStep(models.Model):
    position = models.IntegerField() # so each step is printed in order
    step = models.CharField(max_length=40, help_text='Enter the recipe step')
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, default=1)

    def __str__(self):
        """String for representing the Model object."""
        return self.step

    class Meta:
        ordering = ['position']

class RecipeImage(models.Model):
    top_pic = models.BooleanField(default=False, help_text='Set if this is to be the top image')
    image_path = models.CharField(max_length=40, help_text='Enter the image url')
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, default=1)

    def __str__(self):
        """String for representing the Model object."""
        return self.image_path

catalog/views.py
from django.shortcuts import render
from catalog.models import Recipe, Ingredient, Category, RecipeIngredient
from django.views import generic

# Create your views here.


def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_recipes = Recipe.objects.all().count()
    num_ingredients = Ingredient.objects.all().count()
    num_categories = Category.objects.all().count()

    context = {
        'num_recipes': num_recipes,
        'num_ingredients': num_ingredients,
        'num_categories': num_categories
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)


class RecipeListView(generic.ListView):
    model = Recipe
    paginate_by = 10

class RecipeDetailView(generic.DetailView):
    model = Recipe

    

catalog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
 
  {% block title %}<title>Belle's Vegan Recipe Collection</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'recipes' %}">All recipes</a></li>
          <li><a href="">Categories</a></li>
        </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
  </div>
</body>
</html>

catalog/templates/catalog/recipe_detail.html
{% extends "base.html" %}

{% block content %}
{% load static %}
{% static 'img' as base_url %}
  <h1>{{ recipe.title}}</h1>

  <h3>{{ recipe.description }}</h3>
  <br />

  <b>Ingredients</b>

  {% for recipeingredient in recipe.recipeingredient_set.all %}
  <ul>
    <li>{{ recipeingredient }}</li>
  </ul>
  {% endfor %}

  <br />
  <b>Method</b>
  <br />

  {% for recipestep in recipe.recipestep_set.all %}
    {{ recipestep.position }}.  {{ recipestep }}<br />
  {% endfor %}
  
  {% for recipeimage in recipe.recipeimage_set.all %}
     <img itemprop="image" src="{{base_url}}/{{recipeimage}}" />
  {% endfor %}

{% endblock %}

catalog/templates/catalog/recipe_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Recipe List</h1>
  {% if recipe_list %}
  <ul>
    {% for recipe in recipe_list %}
      <li>
        <a href="{{ recipe.get_absolute_url }}">{{ recipe.title }}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no recipes yet.</p>
  {% endif %}       
{% endblock %}

catalog/templates/index.html
{% extends "base.html" %}

{% block content %}
  <h1>Belle's Vegan Recipe Collection</h1>
  <p>Welcome to my Vegan Recipe Book</p>
  <h2>Dynamic content</h2>
  <p>The Recipe Book has the following record counts:</p>
  <ul>
    <li><strong>Recipes:</strong> {{ num_recipes }}</li>
    <li><strong>Ingredients:</strong> {{ num_ingredients }}</li>
    <li><strong>Categories:</strong> {{ num_categories }}</li>

  </ul>
{% endblock %}